function [params] = set_params(beta, mu, gamma, alpha, b, d)

params = struct('beta',   beta,  ...
                'mu',     mu,    ...
                'gamma',  gamma, ...
                'alpha',  alpha, ...
                'b',      b,     ...
                'd',      d);
